# Dependencies
markdown:         redcarpet
paginate: 5
gems: ["jekyll-minimagick", "jekyll-paginate"]

# Permalinks
permalink:        pretty

# Setup
title:            Comida + Café
tagline:          o que há de melhor no mundo
description:      "Um blog de dois apreciadores do que há de melhor no mundo: comida e café."
url:              http://comidacafe.com.br/index.html
baseurl:          /

author1:
  name:           'Rafael Lopes'
  url:            https://twitter.com/cloudlopes
author2:
  name:           'Santiago Samezima'
  url:            https://twitter.com/samezima

paginate:         5

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/bobeirasa/comidacafe

mini_magick:
    thumbnail:
        source: media/
        destination: media/150/
        resize: "150x150"
    header:
        source: media/
        destination: media/265/
        resize: "265x265"
    default:
        source: media/
        destination: media/712/
        resize: "712x712"
